### ISSUE TITLE
Error after trying to Install the Plugin

### ISSUE THREAD

**Issue by HabubException** [Skryptific/MySweetAlert2#1]
If i click on "Install and Activate" i get a Error: http://prntscr.com/pknamz

**Comment by Skryptific** [comment]
Please make sure you are running PHP 7.x.x

**Comment by Skryptific** [comment]
> If i click on "Install and Activate" i get a Error: http://prntscr.com/pknamz

Please make sure you are running PHP 7.x.x

**Comment by MrRakano** [comment]
same problem here
I'm running PHP 7.2

**Comment by Skryptific** [comment]
> same problem here
> I'm running PHP 7.2
Please provide PHP error logs.

**Comment by Skryptific** [comment]
> same problem here
> I'm running PHP 7.2

Could you please provide me PHP error logs?

**Comment by MrRakano** [comment]
here :
PHP Parse error:  syntax error, unexpected end of file in /public_html/inc/plugins/Skryptec/MySweetAlert2/class.functions.php on line 113

**Comment by Skryptific** [comment]
This issue has been fixed in commit https://github.com/Skryptific/MySweetAlert2/commit/29afd30fd3c0967f42524f882ada9f1dcf922fdd.
